### PR TITLE
feat: add domain url option for private repos

### LINKED ISSUE #20: How to configure this action in case the repo has a private URL?
Hi, I tried this action in a public repo and it works like a charm, in my case the repo is not github.com, it has a private URL in a private organization. For that reason the action is not working as expected. How do I change the repo URL? I believe it's hardcoded here.

https://github.com/jonaslagoni/gh-action-dotnet-bump/blob/c0f5c67b381362a580b70a9885206af1b20ae7af/src/utils.js#L346

```
✖  fatal     remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/repo.git/'

git exited with code 128
```

in this case, `github.com` should point to a private URL.

### PR DESCRIPTION
**Pull request by jalexispoveda**
@jonaslagoni I believe this helps to include private repos. Please take a look and let me know your thoughts. 

Fixes #20

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
LGTM 🔥

You just have a few linting issues to fix 😃

**Comment by jalexispoveda** [comment]
@jonaslagoni I believe it's all set!

**Review by jonaslagoni — APPROVED** [review]
Nice! Thanks for taking the time!

**Comment by jalexispoveda** [comment]
Hi @jonaslagoni , thank you for approving this. How do I make sure I am using the latest version of this? This is what I have but I don't see the new code applied

```- name:  Automated Version Bump
        uses:  joneja09/gh-action-dotnet-bump@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-part: 'Patch'
          path-to-file: 'Mango.Web/Mango.Web.csproj'
          repository-domain: 'test'`

**Pull request merged**
